services:
  backend:
    build: './backend'
    ports:
      - "4001:4001"
    restart: on-failure
    environment:
      - ENVIRONMENT=container
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db